on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install API
        run: |
          cd api
          npm install
          npm run compile
          cd ..
      - name: Build
        run: |
          npm install
          npm install ./api
          npm run compile
      - name: UnitTest
        run: timeout -k 10s 600s npm run unittest-headless

  integration-test:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: |
          cd docker/test
          ln -sf ${{ matrix.os }}.docker headless.docker
          cd -
          timeout -k 10s 600s npm run integrationtest-headless
